# Event Type Constants

MESSAGE_RECEIVED = "MESSAGE_RECEIVED"
ENTRY_STORED = "ENTRY_STORED"
REMINDER_SET = "REMINDER_SET"
REMINDER_FIRED = "REMINDER_FIRED"
SUMMARY_GENERATED = "SUMMARY_GENERATED"
SYNC_RUN = "SYNC_RUN"
ERROR_OCCURRED = "ERROR_OCCURRED"
